name: colcon

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ros:jazzy-ros-core

    steps:
    - name: install tooling dependencies
      run: |
        apt update
        apt -y install --no-install-recommends \
          python3-rosdep \
          python3-vcstool \
          python3-colcon-common-extensions python3-colcon-coveragepy-result \
          git
        rosdep init

    - uses: ros-tooling/action-ros-ci@v0.4
      with:
        target-ros2-distro: jazzy
        import-token: ${{ secrets.GITHUB_TOKEN }}
        rosdep-check: true
